{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fnil\fcharset0 AppleColorEmoji;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 [build]\
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"\
publish = "public"\
\
[build.environment]\
# (Optional) Text in landing page button\
LANDING_BUTTON = "Click to steal some
\f1 \uc0\u55357 \u56390 
\f0 "\
# (Optional) Site description on landing page\
LANDING_DESCRIPTION = "I have nothing but intelligence."\
# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)\
LANDING_PAGE = "home"\
# (Optional) Site title on landing page\
LANDING_TITLE = "I love obsidian-zola! 
\f1 \uc0\u55357 \u56470 
\f0 "\
PYTHON_VERSION = "3.8"\
# (REQUIRED) Site repo URL\
REPO_URL = "https://github.com/koreanstudies/Korean_Study_Vault"\
# (Optional) Site title in navbar\
SITE_TITLE = "Someone's Second 
\f1 \uc0\u55358 \u56800 
\f0 "\
# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)\
SITE_TITLE_TAB = ""\
# (REQUIRED) Netlify site URL\
SITE_URL = "https://gilded-crepe-de4271.netlify.app/"\
# (Optional) Site Timezone\
TIMEZONE = "Asia/Hong_Kong"\
ZOLA_VERSION = "0.15.2"\
# (Optional, default title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.\
SORT_BY = "title"\
# (Optional) Google Analytics Measurement ID\
GANALYTICS = ""\
# (Optional, default true) Slugify URLs. Put "" to disable.\
SLUGIFY = "y"\
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.\
HOME_GRAPH = "y"\
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.\
PAGE_GRAPH = "y"\
# (Optional, default false) Whether sidebar sections should be collapsed by default.\
SIDEBAR_COLLAPSED = ""\
# (Optional, default blank) Additional footer content.\
FOOTER = ""\
# (Optional, default main) Root section name.\
ROOT_SECTION_NAME = "main"\
# (Optional) visjs graph options. Can remove if desired.\
GRAPH_OPTIONS = """\
        \{\
        	nodes: \{\
        		shape: "dot",\
        		color: isDark() ? "#8c8e91" : "#dee2e6",\
        		font: \{\
        			face: "Inter",\
        			color: isDark() ? "#c9cdd1" : "#616469",\
        			strokeColor: isDark() ? "#c9cdd1" : "#616469",\
        		\},\
        		scaling: \{\
        			label: \{\
        				enabled: true,\
        			\},\
        		\},\
        	\},\
        	edges: \{\
        		color: \{ inherit: "both" \},\
        		width: 0.8,\
        		smooth: \{\
        			type: "continuous",\
        		\},\
        		hoverWidth: 4,\
        	\},\
        	interaction: \{\
        		hover: true,\
        	\},\
        	height: "100%",\
        	width: "100%",\
        	physics: \{\
        		solver: "repulsion",\
        	\},\
        \}\
        """}